[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "vscode-html-language-server" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "vscode-html-language-server" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[language-server.omnisharp]
command = "dotnet"
args = [ "/home/matheusandrade/omnisharp/OmniSharp.dll", "--languageserver" ]
